import { Inter } from 'next/font/google'
import './globals.css'
import { menuData } from './util/database'
import './css/menu.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  let menuData = ['Home', 'list', 'Search', 'Setting'];

  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <div className='menu-bg'>
          <ul className='menu-list'>
            {
              menuData.map((item) => {
                return (
                  <li key='item' className='menu-item menu-active'>
                    <span className='menu-tiem__icon'></span>
                    <span className='menu-item__text'>{item}</span>
                  </li>
                )
              })
            }
          </ul>
        </div>
      </body>
    </html>
  )
}
